### ISSUE TITLE
Bekomme keine Verbindung

### ISSUE THREAD

**Issue by Zlupo** [Baumert7269/ioBroker.repetierserver#16]
Hallo habe den Repetier Server in der Version Pro 1.0.3 auf einen Raspberry Pi 3 b+ laufen und einen JGAurora A5s.Ser Server funktioniert soweit gut.
Auf einem Raspberry Pi 4 habe ich dann IoBroker in der aktuellen Version mit dem Repetier Adapter in Version 0.4 und einer Instanz.
Gebe ich die daten des Servers ein  also IP 192.168.178.xxx den Port 3344 und den API Key des Servers ein, speichere die und starte dis Instanz, startet er wird kurz grün und dann wieder rot. In den Objekten hat er die Datenpunkte, auch die des Druckers angelegt, aber es werden keine Daten angezeigt. 
Gebe ich in der Instanz bei der IP http://192.168.178.xxx und den Rest wie zuvor ein, starte die Instanz verbindet sich auch alles und bleibt grün, aber ich bekomme in den Objekten keine Datenpunkte des Druckers.

Was mache ich falsch?

Gruß Zlupo

PS Auch mit Version 0.5 geht es nicht. :-(

**Comment by Robe222** [comment]
Hi, 
ich hatte Version 0.0.3 mit einem Drucker am laufen, nun eine zweiten und es läuft nicht mehr
weder mit 0.0.3 noch mit 0.0.5 Instanz bleibt rot!?! 
0.0.5 bringe ich überhaupt nicht zum laufen, 0.0.3 geht mit einem Drucker (aber das ist zu wenig:))
Bin am Verzweifeln :(
Grüße Robe

**Comment by Baumert7269** [comment]
Hallo,
ich bin an der neuen Version dran, bitte noch etwas Geduld.

Grüße
Baumert7269


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Robe222<mailto:notifications@github.com>
Gesendet: Mittwoch, 10. März 2021 12:55
An: Baumert7269/ioBroker.repetierserver<mailto:ioBroker.repetierserver@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [Baumert7269/ioBroker.repetierserver] Bekomme keine Verbindung (#16)


Hi,
ich hatte Version 0.0.3 mit einem Drucker am laufen, nun eine zweiten und es läuft nicht mehr
weder mit 0.0.3 noch mit 0.0.5 Instanz bleibt rot!?!
0.0.5 bringe ich überhaupt nicht zum laufen, 0.0.3 geht mit einem Drucker (aber das ist zu wenig:))
Bin am Verzweifeln :(
Grüße Robe

**Comment by n0rdl1cht** [comment]
Ich glaube ich habe das selbe Fehlerbild, auch mit der 0.0.5. 

Ich habe hier mal einen Auszug aus meinem Log, in der Hoffnung das dies hilft das Problem einzukreisen.

repetierserver.0	2021-06-09 11:27:20.863	warn	(2445) State "repetierserver.0.info.printjob" has no existing object, this might lead to an error in future versions
repetierserver.0	2021-06-09 11:27:20.862	warn	(2445) State "repetierserver.0.info.active" has no existing object, this might lead to an error in future versions
repetierserver.0	2021-06-09 11:27:20.806	warn	(2445) Terminated (UNCAUGHT_EXCEPTION): Without reason
repetierserver.0	2021-06-09 11:27:20.805	info	(2445) terminating
repetierserver.0	2021-06-09 11:27:20.804	info	(2445) Repetier-Server-Verbindung beendet ...
repetierserver.0	2021-06-09 11:27:20.803	info	(2445) Repetier-Server-Verbindung beendet ...
repetierserver.0	2021-06-09 11:27:20.802	info	(2445) Repetier-Server-Service bereinigt ...
repetierserver.0	2021-06-09 11:27:20.752	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.751	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.extendObject (/opt/iobroker/node_m
repetierserver.0	2021-06-09 11:27:20.749	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.749	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.747	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.746	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.setObjectNotExists (/opt/iobroker/
repetierserver.0	2021-06-09 11:27:20.745	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.744	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.707	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.707	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.extendObject (/opt/iobroker/node_m
repetierserver.0	2021-06-09 11:27:20.706	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.705	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.704	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.703	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.setObjectNotExists (/opt/iobroker/
repetierserver.0	2021-06-09 11:27:20.702	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.701	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.668	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.667	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.extendObject (/opt/iobroker/node_m
repetierserver.0	2021-06-09 11:27:20.666	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.665	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.663	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.663	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.setObjectNotExists (/opt/iobroker/
repetierserver.0	2021-06-09 11:27:20.661	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.660	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.612	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.611	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.extendObject (/opt/iobroker/node_m
repetierserver.0	2021-06-09 11:27:20.610	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.609	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.605	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.604	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.setObjectNotExists (/opt/iobroker/
repetierserver.0	2021-06-09 11:27:20.602	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.601	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.496	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.495	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.extendObject (/opt/iobroker/node_m
repetierserver.0	2021-06-09 11:27:20.494	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.493	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.491	error	(2445) The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.490	error	(2445) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Template.setObjectNotExists (/opt/iobroker/
repetierserver.0	2021-06-09 11:27:20.485	error	(2445) unhandled promise rejection: The id is empty! Please provide a valid id.
repetierserver.0	2021-06-09 11:27:20.485	error	(2445) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
repetierserver.0	2021-06-09 11:27:20.402	debug	(2445) RepetierServer states subscribed
repetierserver.0	2021-06-09 11:27:20.400	info	(2445) undefined 3344
repetierserver.0	2021-06-09 11:27:20.400	info	(2445) undefined HIER STEHT MEIN GEHEIMER API SCHLÜSSEL
repetierserver.0	2021-06-09 11:27:20.399	info	(2445) undefined HIER STEHT MEINE GEHEIME IP ADRESSE
repetierserver.0	2021-06-09 11:27:20.398	info	(2445) undefined
repetierserver.0	2021-06-09 11:27:20.338	info	(2445) starting. Version 0.0.5 in /opt/iobroker/node_modules/iobroker.repetierserver, node: v14.2.0, js-controller: 3.2.16
repetierserver.0	2021-06-09 11:27:19.955	debug	(2445) statesDB connected
repetierserver.0	2021-06-09 11:27:19.953	debug	(2445) States connected to redis: 127.0.0.1:9000
repetierserver.0	2021-06-09 11:27:19.937	debug	(2445) States create User PubSub Client
repetierserver.0	2021-06-09 11:27:19.935	debug	(2445) States create System PubSub Client
repetierserver.0	2021-06-09 11:27:19.915	debug	(2445) Redis States: Use Redis connection: 127.0.0.1:9000
repetierserver.0	2021-06-09 11:27:19.912	debug	(2445) objectDB connected
repetierserver.0	2021-06-09 11:27:19.897	debug	(2445) Objects connected to redis: 127.0.0.1:9001
repetierserver.0	2021-06-09 11:27:19.870	debug	(2445) Objects client initialize lua scripts
repetierserver.0	2021-06-09 11:27:19.869	debug	(2445) Objects create User PubSub Client
repetierserver.0	2021-06-09 11:27:19.867	debug	(2445) Objects create System PubSub Client
repetierserver.0	2021-06-09 11:27:19.864	debug	(2445) Objects client ready ... initialize now
repetierserver.0	2021-06-09 11:27:19.800	debug	(2445) Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by Baumert7269** [comment]
Problem sollte mit der Version 0.0.6 behoben sein.
