### ISSUE TITLE
Nur Version 0.0.1 läuft

### ISSUE THREAD

**Issue by funboxbolzer** [Baumert7269/ioBroker.repetierserver#18]
Hi. ich habe heute meinen ganzen iobroker geupdatet.
Wahrscheinlich mein größter Fehler seit langem.....

ich wollte den Repetieradapter installieren. Leider kann ich nur die Version 0.0.1 verwenden.

Alle anderen laufen in eine Verbindungsschleife....

Was kann ich hier tun?

**Comment by Baumert7269** [comment]
Problem sollte mit der Version 0.0.6 behoben sein.
