### ISSUE TITLE
Cannot read property 'val' of null

### ISSUE THREAD

**Issue by Michaelheus** [Baumert7269/ioBroker.repetierserver#22]
Adapter starts working and runs directly into the issue.

![repetier](https://user-images.githubusercontent.com/26620658/120898514-73957480-c62b-11eb-803a-ff165ac1636e.PNG)

**Versions:**  
 - Adapter version: 0.0.5
 - JS-Controller version: 3.1.6
 - Node version: 12.20.0
 - Operating system: Linux iobroker 5.4.73-1-pve

**Comment by Baumert7269** [comment]
Problem sollte mit der Version 0.0.6 behoben sein.
