### ISSUE TITLE
ERROR and missing States

### ISSUE THREAD

**Issue by skvarel** [Baumert7269/ioBroker.repetierserver#6]
Ich bekomme folgende Fehler:

![grafik](https://user-images.githubusercontent.com/1114419/81919988-d52a1180-95d8-11ea-85c2-cd0b19620f48.png)

System:
js-controller 3.1.4
Node.js v12.16.3

.. und mir fehlen ein paar Datenpunkte.

Der Drucker mit der Repetier-Firmware wird gut angezeigt. Die 3 Marlin Drucker nicht.

![grafik](https://user-images.githubusercontent.com/1114419/81920273-42d63d80-95d9-11ea-9103-78580f67d598.png)

![grafik](https://user-images.githubusercontent.com/1114419/81920328-541f4a00-95d9-11ea-8d81-a62730e28b70.png)

**Comment by timelesss** [comment]
Ich habe das gleiche Problem.

![grafik](https://user-images.githubusercontent.com/4747782/83141065-590eee00-a0ef-11ea-8a6c-31db324c7a3a.png)

**Comment by skvarel** [comment]
Der Fehler besteht immer noch ... Version: 0.0.3 obwohl es laut Channel-Log behoben sein soll

![grafik](https://user-images.githubusercontent.com/1114419/104558599-5bed2d80-5643-11eb-980f-cd4c18840788.png)

**Comment by Baumert7269** [comment]
Hallo zusammen, entschuldigt die wirklich sehr späte Nachricht. Ich schaue mir das Problem mal genau an.

**Comment by Jetiman** [comment]
Wird an dem Fehler noch gearbeitet? Ich habe mit aktueller Version den gleiche Fehler.

**Comment by skvarel** [comment]
Ich habe wieder auf den Adapter von Coyote gewechselt. Der läuft zuverlässig bei meinen 3 Druckern und dem Laser. Ich bekomme diesen Adapter einfach nicht iun den Griff :(

**Comment by Baumert7269** [comment]
Problem sollte mit der Version 0.0.6 behoben sein.
